### PR TITLE
Support for event emits on in-dom templates

### PR DESCRIPTION
**Pull request by KelvinCampelo**
change the emit events names to kebab-case to works on in-dom templates

### CODE REVIEW

**Comment by KelvinCampelo** [comment]
Just to remember, this pull request also can still use the camelCase

[Link to vuejs documentation](https://vuejs.org/v2/guide/components-custom-events.html)

**Comment by aquilesb** [comment]
You right, the events should be kebab-case. Unfortunately, this will break the unit tests (right now it is not breaking because package.json was wrong, So travis never call them. I already fixed on master). Could update the unit tests? Otherwise tomorrow I probably will have time to do it. Thanks

**Comment by KelvinCampelo** [comment]
Okay @aquilesb I've done the update of unit tests. Now you can merge.

**Comment by aquilesb** [comment]
Thanks

**Pull request merged**
