### PR TITLE
Display with html

### PR DESCRIPTION
**Pull request by huypn**
Resolved  issue to show format with html tag.

### CODE REVIEW

**Comment by aquilesb** [comment]
Hi @huypn, thanks for the PR. I didn't understand which you are trying to achieve, what was the bug you have fixed. I have checked your modifications and you are adding a new `div` inside each `td` element. This should not be the default behavior, the default behavior is print the formated value directly inside the `td`. If you need a div inside the `td`, I recommend you to use the `slot actions`. With them, you can render any component inside the `td` and have access to the row data. You can find examples of that on the demos.

**Comment by huypn** [comment]
Hello @aquilesb,
I added this because when use format for td then I have to use some html tag, and if use your current code then it will not render as html.
This is just for allow display as html code.
Ex: I want to show price but with span <span style="color: red">$100</span>
then instead display $100 with color red then it show full : <span style="color: red">$100</span>
I added tag div to use v-html, template do not allow to add v-html.

**Comment by aquilesb** [comment]
Hey @huypn, I got your point. As I said before, this can't be the default behavior, the default behavior should be to render the data directly in the `<td>`. To solve that, you can use the actions, maybe the name does not reflect perfectly how it can be used. You only have to add a string in your headerFields like: `__slot:actions:actionFirst`. In your template, inside the `<DataTable>` component you declare your slot for that column like:  ```<div v-slot:actionFirst="props" v-html="props.rowData.value"></div>```. You can check an example [here](https://codepen.io/aquilesb/pen/wVaBPv). Search for `__slot:actions:actionFirst`.

**Comment by aquilesb** [comment]
@huypn If you need help to achieve that, open an issue, and I can help you. I will close this PR because I have no intention of replacing the `template` by `div`

**Pull request closed without merging**
